name: relax
description: relax application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  animations: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  audioplayers: ^0.18.3
  intl: ^0.17.0
  flare_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/city/
    - assets/images/meditation/
    - assets/images/forest/
    - assets/images/rain/
    - assets/audios/
    - assets/animation/
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

